/*
 * This file is part of bitfireAT/synctools which is released under GPLv3.
 * Copyright © All Contributors. See the LICENSE and AUTHOR files in the root directory for details.
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package at.bitfire.synctools.icalendar

import net.fortuna.ical4j.model.Parameter
import net.fortuna.ical4j.model.parameter.TzId
import net.fortuna.ical4j.model.property.DateProperty
import java.time.ZoneId
import java.time.ZonedDateTime
import java.time.temporal.Temporal
import kotlin.jvm.optionals.getOrNull

object DatePropertyTzMapper {

    /**
     * Normalizes the date property by converting ical4j-based timezones to system timezones.
     *
     * If the date is a ZonedDateTime with an ical4j-specific timezone, it attempts to replace it with a system timezone.
     * If the TZID parameter is available and matches a system timezone, the date is adjusted to use that timezone.
     * Otherwise, the date is converted to the system default timezone.
     *
     * For non-ZonedDateTime types (e.g., Instant, LocalDate, OffsetDateTime), the original date is returned unchanged.
     *
     * @return The normalized date with system timezone (if applicable) or the original date if no conversion is needed.
     */
    fun <T : Temporal> DateProperty<T>.normalizedDate(): T {
        /* This date is generated by ical4j's TemporalAdapter and uses ical4j-based timezones
        for ZonedDateTimes. */
        val ical4jDate: T = date

        if (ical4jDate is ZonedDateTime) {
            /* In case of ZonedDateTime, date.zone.id will look like "ical4j~<uuid>" (if taken from
            ical4j database) or "ical4j-local-xxx" (if generated from VTIMEZONE). We want to
            replace such ical4j-based timezones by system timezones because the calendar provider
            needs a system timezone ID. */

            // Get TZID value (if available), for instance "Europe/Vienna"
            val tzId = getParameter<TzId>(Parameter.TZID).getOrNull()?.value

            if (tzId != null && ZoneId.getAvailableZoneIds().contains(tzId)) {
                // TODO: We could use heuristics or static mappings to map known TZIDs to system timezone IDs.

                // Timezone with this TZID is available in system, we want to use the same time string
                // ("ddmmyyyyTHHMMSS"), but with that timezone.
                val systemTz = ZoneId.of(tzId)
                return ical4jDate.withZoneSameLocal(systemTz) as T
            } else {
                // Timezone with this TZID is not known by system, fall back to same timestamp, but
                // with system default timezone.
                return ical4jDate.withZoneSameInstant(ZoneId.systemDefault()) as T
            }
        } else {
            // return Instant, LocalDate/..., OffsetDateTime as it is
            return ical4jDate
        }
    }

}