/*
 * This file is part of bitfireAT/synctools which is released under GPLv3.
 * Copyright © All Contributors. See the LICENSE and AUTHOR files in the root directory for details.
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package at.bitfire.synctools.icalendar

import net.fortuna.ical4j.model.Parameter
import net.fortuna.ical4j.model.parameter.TzId
import net.fortuna.ical4j.model.property.DateProperty
import java.time.ZoneId
import java.time.ZonedDateTime
import java.time.temporal.Temporal
import kotlin.jvm.optionals.getOrNull

object DatePropertyTzMapper {

    /**
     * Normalizes the date property by converting ical4j-based timezones to system timezones.
     *
     * For non-ZonedDateTime types (e.g., Instant, LocalDate, OffsetDateTime), the original date is
     * returned unchanged.
     *
     * If the date is a ZonedDateTime with an ical4j-specific/custom timezone, it's replaced with a
     * system timezone:
     *
     * - If the TZID parameter matches a system timezone, the date is adjusted
     * to the same local values (year/month/day/hour/minute/second) + system timezone.
     * - Otherwise, the timestamp is calculated from the custom timezone and the date is adjusted
     * to the same timestamp + system default timezone.
     *
     * @return The normalized date that is guaranteed to use a system timezone ID (if it references
     * at a timezone at all).
     */
    fun <T : Temporal> DateProperty<T>.normalizedDate(): T {
        /* This date is generated by ical4j's TemporalAdapter and uses ical4j-based timezones
        for ZonedDateTimes. */
        val ical4jDate: T = date

        if (ical4jDate is ZonedDateTime) {
            /* In case of ZonedDateTime, date.zone.id will look like "ical4j~<uuid>" (if taken from
            ical4j database) or "ical4j-local-xxx" (if generated from VTIMEZONE). We want to
            replace such ical4j-based timezones by system timezones because the content providers
            need a system timezone ID. */

            // Get TZID value (if available), for instance "Europe/Vienna"
            val tzId = getParameter<TzId>(Parameter.TZID).getOrNull()?.value

            // Get corresponding system TZID (usually the same – "Europe/Vienna" in our example)
            val systemTzId = systemTzId(tzId)
            if (systemTzId != null) {
                // Timezone is known by system, we want to use the same time string
                // ("ddmmyyyyTHHMMSS"), but with the system timezone instead of the ical4j timezone.
                val systemTz = ZoneId.of(tzId)
                return ical4jDate.withZoneSameLocal(systemTz) as T
            } else {
                // Timezone is not known by system, fall back to same timestamp, but
                // with system default timezone.
                return ical4jDate.withZoneSameInstant(ZoneId.systemDefault()) as T
            }
        } else {
            // return Instant, LocalDate/..., OffsetDateTime as it is
            return ical4jDate
        }
    }

    /**
     * Attempts to find a matching system timezone ID for the given original timezone ID.
     *
     * This method first checks for an exact case-insensitive match among the available system timezone IDs.
     * If no exact match is found, it then searches for a partial match where either the system ID contains
     * the original ID or vice versa (case-insensitive comparison).
     *
     * @param origTzId The original timezone ID to match against system timezone IDs. Can be null.
     * @return The matching system timezone ID if found, otherwise null. Returns null if the input is null.
     */
    private fun systemTzId(origTzId: String?): String? {
        if (origTzId == null)
            return null

        val systemIds = ZoneId.getAvailableZoneIds()
        // First, try to find an exact match (case-insensitive)
        if (systemIds.any { origTzId.equals(it, ignoreCase = true) })
            return origTzId

        // Otherwise, try to find a partial match (sometimes the origTzId is something like
        // "/freeassociation.sourceforge.net/Tzfile/Europe/Vienna")
        for (systemId in systemIds) {
            val systemIdContainsOrigId = systemId.lowercase().contains(origTzId.lowercase())
            val origIdContainsSystemId = origTzId.lowercase().contains(systemId.lowercase())
            if (systemIdContainsOrigId || origIdContainsSystemId)
                return systemId
        }

        // No result
        return null
    }

}